# appveyor.yml
image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python312"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - cmd: "%PYTHON%\\python.exe -m pip install pyinstaller moviepy whisper tqdm numpy imageio_ffmpeg"

script:
  - cmd: build_pyinstaller.bat

artifacts:
  - path: dist\voice_cutter_gui.exe
    name: voice_cutter_gui.exe
