version: 1.0.{build}
image: Visual Studio 2022

install:
  # 升級 pip 並安裝所有相依
  - python -m pip install --upgrade pip
  - pip install moviepy whisper tqdm numpy pyinstaller

  # 只在 hooks 不存在時才建立，並新增解決 MoviePy 動態匯入的 custom hook
  - if not exist hooks mkdir hooks
  - echo from PyInstaller.utils.hooks import collect_submodules, collect_data_files > hooks\hook-moviepy.py
  - echo hiddenimports = collect_submodules('moviepy') >> hooks\hook-moviepy.py
  - echo datas = collect_data_files('moviepy', include_py_files=True) >> hooks\hook-moviepy.py

build_script:
  # 用 one-dir 模式打包，確保 moviepy.editor 及所有資料都在 dist\VoiceCutterGUI\ 資料夾
  - pyinstaller --clean --onedir --noconsole --additional-hooks-dir hooks --collect-all whisper --collect-all imageio_ffmpeg --name VoiceCutterGUI voice_cutter_gui.py

  # 壓縮整個 dist\VoiceCutterGUI\ 生成 zip
  - powershell -Command "Compress-Archive -Path '.\\dist\\VoiceCutterGUI\\*' -DestinationPath '.\\dist\\VoiceCutterGUI.zip'"

artifacts:
  # 將 ZIP 上傳為 artifact，下載後解壓就能直接執行
  - path: dist\VoiceCutterGUI.zip
    name: VoiceCutterGUI
