# 使用 Visual Studio 2022 環境
image: Visual Studio 2022

# 指定 Python 路徑
environment:
  PYTHON: 'C:\Python311'

# 安裝相依套件
install:
  - '%PYTHON%\python.exe -m pip install --upgrade pip'
  - '%PYTHON%\python.exe -m pip install pyinstaller moviepy whisper tqdm numpy imageio_ffmpeg'

# 打包腳本（呼叫自訂的 build_pyinstaller.bat）
build_script:
  - 'call build_pyinstaller.bat'

# 測試腳本：執行 exe 並將輸出／錯誤導入日誌
test_script:
  - '%PYTHON%\python.exe dist\voice_cutter_gui.exe --help > voice_cutter_gui.log 2>&1 || echo 執行失敗，詳見 voice_cutter_gui.log'

# 收集產物：執行檔和日誌
artifacts:
  - path: dist\voice_cutter_gui.exe
    name: voice_cutter_gui.exe
  - path: voice_cutter_gui.log
    name: voice_cutter_gui.log
