version: 1.0.{build}
image: Visual Studio 2022

install:
  # 安装 CI 上需要的 Python package
  - python -m pip install --upgrade pip
  - pip install nuitka moviepy whisper tqdm numpy imageio_ffmpeg

build_script:
  # 调用上面那个 bat 脚本（它会编译出 voice_cutter_gui.exe）
  - call build_nuitka.bat

artifacts:
  # 上传最终的 EXE 作为 artifact
  - path: voice_cutter_gui.exe
    name: VoiceCutterGUI.exe
