version: 1.0.{build}
image: Visual Studio 2022

debug:
  - BUILD_DEBUG=1

install:
  - cmd: build_pyinstaller.bat

build_script:
  - echo Packaging done

artifacts:
  - path: dist\voice_cutter_gui.dist\**
    name: VoiceCutterGUI
