# AppVeyor CI 設定檔
image: Visual Studio 2022

environment:
  # 指定要用哪一版 Python
  PYTHON: "C:\\Python311"

install:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: "%PYTHON%\\python.exe" -m pip install --upgrade pip
  - cmd: pip install pyinstaller moviepy whisper tqdm numpy imageio_ffmpeg

build:
  # 呼叫下方提供的打包腳本
  - cmd: call build_pyinstaller.bat

test:
  # 執行產出的 exe，將標準輸出 & 錯誤都導到日誌
  - cmd: dist\voice_cutter_gui.exe --help > voice_cutter_gui.log 2>&1 || echo "執行失敗，詳見 voice_cutter_gui.log"

artifacts:
  - path: dist\voice_cutter_gui.exe
  - path: voice_cutter_gui.log
