version: 1.0.{build}
image: Visual Studio 2022

environment:
  - BUILD_DEBUG=1

install:
  - cmd: build_pyinstaller.bat

build_script:
  - cmd: echo Packaging done

artifacts:
  - path: distoice_cutter_gui.dist\**
    name: VoiceCutterGUI
