name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 安裝 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝相依套件
        run: |
          python -m pip install --upgrade pip
          pip install moviepy whisper tqdm numpy pyinstaller

      - name: 建立 hooks 目錄並新增 hook-moviepy.py
        run: |
          mkdir hooks
          echo from PyInstaller.utils.hooks import collect_submodules, collect_data_files > hooks\hook-moviepy.py
          echo hiddenimports = collect_submodules('moviepy') >> hooks\hook-moviepy.py
          echo datas = collect_data_files('moviepy', include_py_files=True) >> hooks\hook-moviepy.py

      - name: 執行 PyInstaller 打包
        run: |
          pyinstaller --clean --onefile --noconsole ^
            --additional-hooks-dir hooks ^
            --collect-all whisper ^
            --collect-all imageio_ffmpeg ^
            --name VoiceCutterGUI ^
            voice_cutter_gui.py

      - name: 上傳 Windows 可執行檔
        uses: actions/upload-artifact@v3
        with:
          name: VoiceCutterGUI.exe
          path: dist/VoiceCutterGUI.exe
