name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 安裝 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝相依套件
        run: |
          python -m pip install --upgrade pip
          pip install moviepy whisper tqdm numpy pyinstaller

      - name: 新增 MoviePy 自訂 Hook
        run: |
          mkdir hooks
          cat << 'EOF' > hooks/hook-moviepy.py
from PyInstaller.utils.hooks import collect_submodules, collect_data_files
hiddenimports = collect_submodules('moviepy')
datas = collect_data_files('moviepy', include_py_files=True)
EOF

      - name: 執行 PyInstaller 打包
        run: |
          pyinstaller --clean --onefile --noconsole \
            --additional-hooks-dir hooks \
            --collect-all whisper \
            --collect-all imageio_ffmpeg \
            --name VoiceCutterGUI \
            voice_cutter_gui.py

      - name: 上傳 Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VoiceCutterGUI.exe
          path: dist/VoiceCutterGUI.exe
